language: python
python:
  - "3.8"
# command to install dependencies
before_install:
  - pip install pre-commit

stages:
  - Pre-commit
  - Docker CI

branches:
  only:
    - main

services:
  - docker

notifications:
  email: false

jobs:
  include:
    - stage: "Pre-commit"
      script:
        - pre-commit install
        - pre-commit run --all-files
    - stage: "Docker CI"
      name: "Docker build/push"
      script:
        - docker build -t armadik/dash .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push armadik/dash
