language: python
python:
  - "3.8"

env:
  global:
    - HELM_URL=https://get.helm.sh
    - HELM_TGZ=helm-v3.7.0-rc.3-linux-amd64.tar.gz

# command to install dependencies
before_install:
  - pip install pre-commit
install:
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  # Installig pip deps
  - sudo pip install yamllint=="${YAMLLINT_VERSION}"
  - pip install pre-commit

stages:
  - Pre-commit
  - Docker CI

branches:
  only:
    - main

services:
  - docker

notifications:
  email: false

jobs:
  include:
    - stage: "Pre-commit"
      script:
        - pre-commit install
        - pre-commit run --all-files
    - stage: "Docker CI"
      name: "Docker build/push"
      script:
        - docker build -t armadik/dash .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push armadik/dash
