language: python
python:
  - "3.8"
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install pre-commit

script:
  - echo "$TRAVIS_BUILD_ID"

branches:
  only:
    - main
services:
  - docker

before_install:
  - python -m pip install --upgrade pip
  - echo "### test ###"
  - env

jobs:
  include:
    - stage: "Docker build"
      name: "Docker build"
      script:
        - docker build -t armadik/dash .
    - stage: "Docker push"
      name: "Docker push"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push armadik/dash
