language: python
python:
  - "3.8"
# command to install dependencies
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install pre-commit

script:
  - pre-commit install
  - pre-commit run --all-files

branches:
  only:
    - main

services:
  - docker

jobs:
  include:
    - stage: "Docker build"
      name: "Docker build"
      script:
        - docker build -t armadik/dash .
    - stage: "Docker push"
      name: "Docker push"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push armadik/dash
