apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:  {{- include "dash.labels" . | nindent 4 }}
    {{- with .Values.podAnnotations }}
    {{- . | toYaml | nindent 8 }}
    {{- end }}
  namespace: {{ template "dash.namespace" . }}
  annotations:
    {{- /* This lets us autorestart when the secret changes! */}}
    {{- with .Values.podAnnotations }}
    {{- . | toYaml | nindent 8 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dash.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
