{{- if .Values.dashRoute.enable }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:  {{- include "dash.labels" . | nindent 4 }}
  namespace: {{ template "dash.namespace" . }}
spec:
  to:
    kind: Service
    name: {{ .Values.podPortName }}
    weight: 100
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
