apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{ include "dash.labels" . | nindent 4 }}
  namespace: {{ template "dash.namespace" . }}
spec:
  ports:
    - name: {{ .Values.podPortName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector: {{ include "dash.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  type: ClusterIP
