## --  the deployment namespace
namespaceOverride: ""

image:
  repository: armadik/dash
  tag: latest
  sha: ""
  pullPolicy: IfNotPresent

  # pullSecrets:
  #   - myRegistrKeySecretName

# --  POD replica
replicaCount: 2

# -- Parameters service.yaml
service:
  type: ClusterIP
  port: 8050
  annotations: {}
  labels: {}
  portName: service

podPortName: dash

podAnnotations: {}

podlabels: {}

# -- Create route
dashRoute:
  enable: false

# -- Check pod livenessProbe
livenessProbe:
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
# --  Check pod readinessProb
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# -- Ресурсы для POD
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
