## --  the deployment namespace
namespaceOverride: ""

image:
  pullSecrets: ""
  repository: armadik/dash
  tag: latest
  sha: ""
  pullPolicy: IfNotPresent

  # pullSecrets:
  #   - myRegistrKeySecretName

# -- Колличество POD
replicaCount: 2

# -- Параметры service.yaml
service:
  type: ClusterIP
  port: 8050
  annotations: {}
  labels: {}
  portName: service

podPortName: dash

# -- Create route
dashRoute:
  enable: false

# -- Check pod
livenessProbe:
  enabled: true
  dashInitialDelaySeconds: 30
  dashPeriodSeconds: 10
  dashTimeoutSeconds: 5
  dashSuccessThreshold: 1
  dashFailureThreshold: 2
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
# -- Параметры проверки готовности контейнера
readinessProbe:
  enabled: true
  dashInitialDelaySeconds: 30
  dashPeriodSeconds: 7
  dashTimeoutSeconds: 2
  dashSuccessThreshold: 1
  dashFailureThreshold: 5
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# -- Ресурсы для POD
resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi
