## --  the deployment namespace
namespaceOverride: ""

image:
  repository: armadik/dash
  tag: latest
  sha: ""
  pullPolicy: IfNotPresent

  # pullSecrets:
  #   - myRegistrKeySecretName

# --  POD replica
replicaCount: 2

# -- Parameters service.yaml
service:
  type: ClusterIP
  port: 8050
  annotations: {}
  labels: {}
  portName: service

podPortName: dash

podAnnotations: {}

podlabels: {}

# -- Create route
dashRoute:
  enable: true

# --  Check pod readinessProb
readinessProbe:
  httpGet:
    path: /
    port: 8050

# -- Check pod livenessProbe
livenessProbe:
  httpGet:
    path: /
    port: 8050
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10


# -- Ресурсы для POD
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
